name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Resume.tex
      - name: Upload pdf file    
        uses: actions/upload-artifact@v2
        with:
         name: PDF
         path: Resume.pdf
      - name: Download Resume.pdf   
        uses: actions/download-artifact@v2
        with:
          name: Resume.pdf
      - name: Display structure of downloaded files
        run: ls -R   

